CREATE OR REPLACE PACKAGE PF_LINEAS_FACTURA AS
    PROCEDURE ALTA_LINEA(P_COD_FACTURA IN NUMBER,P_COD_PRODUCTO IN NUMBER, UNIDADES IN NUMBER, P_FECHA IN VARCHAR2);
    PROCEDURE BAJA_LINEA(P_COD_FACTURA IN NUMBER,P_COD_PRODUCTO IN NUMBER);
    PROCEDURE MOD_PRODUCTO(P_COD_FACTURA IN NUMBER, P_COD_PRODUCTO IN NUMBER, INPUT IN VARCHAR2);
    FUNCTION NUM_LINEA(P_COD_FACTURA IN NUMBER) RETURN NUMBER;
END PF_LINEAS_FACTURA;

CREATE OR REPLACE PACKAGE BODY PF_LINEAS_FACTURA AS
    PROCEDURE ALTA_LINEA(P_COD_FACTURA IN NUMBER,P_COD_PRODUCTO IN NUMBER, UNIDADES IN NUMBER, P_FECHA IN VARCHAR2)IS
        COD NUMBER;
        PRODUCTO PRODUCTOS%ROWTYPE;
    BEGIN
        SELECT COD_FACTURA INTO COD FROM FACTURAS WHERE COD_FACTURA = P_COD_FACTURA;
        SELECT * INTO PRODUCTO FROM PRODUCTOS WHERE COD_PRODUCTO = P_COD_PRODUCTO;
        IF COD IS NOT NULL AND PRODUCTO.COD_PRODUCTO IS NOT NULL THEN
            INSERT INTO LINEAS_FACTURA VALUES (P_COD_FACTURA, P_COD_PRODUCTO, PRODUCTO.PVP,UNIDADES,CONVERT_TO_DATE(P_FECHA));
        END IF;
        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                RAISE_APPLICATION_ERROR(-20000, 'UNO DE LOS CODIGOS NO EXISTE');
    END ALTA_LINEA;

    PROCEDURE BAJA_LINEA(P_COD_FACTURA IN NUMBER,P_COD_PRODUCTO IN NUMBER) IS
    BEGIN
        DELETE FROM LINEAS_FACTURA WHERE COD_PRODUCTO = P_COD_PRODUCTO AND COD_PRODUCTO = P_COD_PRODUCTO;
    END BAJA_LINEA;

    PROCEDURE MOD_PRODUCTO(P_COD_FACTURA IN NUMBER, P_COD_PRODUCTO IN NUMBER, INPUT IN VARCHAR2) IS
        V_NUMBER NUMBER;
    BEGIN
        V_NUMBER:=TO_NUMBER(INPUT);
        IF V_NUMBER IS NOT NULL THEN
            UPDATE LINEAS_FACTURA SET UNIDADES = V_NUMBER WHERE COD_FACTURA = P_COD_FACTURA AND COD_PRODUCTO = P_COD_PRODUCTO;
        END IF;
        EXCEPTION
        WHEN VALUE_ERROR THEN
            UPDATE LINEAS_FACTURA SET FECHA = CONVERT_TO_DATE(INPUT) WHERE COD_FACTURA = P_COD_FACTURA AND COD_PRODUCTO = P_COD_PRODUCTO;
    END MOD_PRODUCTO;
    
    FUNCTION NUM_LINEA(P_COD_FACTURA IN NUMBER) RETURN NUMBER IS
        V_COUNT NUMBER;
    BEGIN
        SELECT COUNT(*) INTO V_COUNT FROM LINEAS_FACTURA WHERE COD_FACTURA=P_COD_FACTURA;
        RETURN V_COUNT;
    END NUM_LINEA;
END PF_LINEAS_FACTURA;

--PRUEBAS
SET SERVEROUTPUT ON
DECLARE 
    COUNT_FACTURAS_DATE NUMBER;
BEGIN
    --pf_LINEAS_FACTURA.alta_LINEA(2,1,25,'2023-10-17');
    --pf_LINEAS_FACTURA.baja_LINEA(2,1);
    --pf_LINEAS_FACTURA.mod_producto(2,1,'50');
    --pf_LINEAS_FACTURA.mod_producto(2,1,'2023-10-10');
    COUNT_FACTURAS_DATE:=pf_LINEAS_FACTURA.num_linea(2);
    DBMS_OUTPUT.PUT_LINE(COUNT_FACTURAS_DATE);
END;