CREATE OR REPLACE PACKAGE PF_GESTION_FACTURAS AS
    PROCEDURE ALTA_FACTURA(P_COD_FACTURA IN NUMBER, P_FECHA IN VARCHAR2, P_DESCRIPCION IN VARCHAR2);
    PROCEDURE BAJA_FACTURA(P_COD_FACTURA IN NUMBER);
    PROCEDURE MOD_DESCRI(P_COD_FACTURA IN NUMBER, P_DESCRIPCION IN VARCHAR2);
    PROCEDURE MOD_FECHA(P_COD_FACTURA IN NUMBER, P_FECHA IN VARCHAR2);
    FUNCTION NUM_FACTURA(P_FECHA_INICIO IN VARCHAR2, P_FECHA_FINAL IN VARCHAR2) RETURN NUMBER;
    FUNCTION TOTAL_FACTURA(P_COD_FACTURA IN NUMBER) RETURN NUMBER;
END PF_GESTION_FACTURAS;

CREATE OR REPLACE PACKAGE BODY PF_GESTION_FACTURAS AS
    PROCEDURE ALTA_FACTURA(P_COD_FACTURA IN NUMBER, P_FECHA IN VARCHAR2, P_DESCRIPCION IN VARCHAR2) IS
        COD NUMBER;
    BEGIN
        SELECT COD_FACTURA INTO COD FROM FACTURAS WHERE COD_FACTURA = P_COD_FACTURA;
        IF COD IS NOT NULL THEN
            RAISE_APPLICATION_ERROR(-20000, 'EL CODIGO YA EXISTE');
        END IF;
        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                INSERT INTO FACTURAS VALUES (P_COD_FACTURA, CONVERT_TO_DATE(P_FECHA), P_DESCRIPCION);
    END ALTA_FACTURA;

    PROCEDURE BAJA_FACTURA(P_COD_FACTURA IN NUMBER) IS
        V_COUNT NUMBER;
    BEGIN
        SELECT COUNT(*) INTO V_COUNT FROM LINEAS_FACTURA WHERE COD_FACTURA=P_COD_FACTURA;
        IF V_COUNT > 0 THEN
            DELETE FROM LINEAS_FACTURA WHERE COD_FACTURA = P_COD_FACTURA;
        END IF;
            DELETE FROM FACTURAS WHERE COD_FACTURA = P_COD_FACTURA;
    END BAJA_FACTURA;

    PROCEDURE MOD_DESCRI(P_COD_FACTURA IN NUMBER, P_DESCRIPCION IN VARCHAR2) IS
    BEGIN
        UPDATE FACTURAS SET DESCRIPCION = P_DESCRIPCION WHERE COD_FACTURA = P_COD_FACTURA;
    END MOD_DESCRI;
    
    PROCEDURE MOD_FECHA(P_COD_FACTURA IN NUMBER, P_FECHA IN VARCHAR2)IS
    BEGIN
        UPDATE FACTURAS SET FECHA = CONVERT_TO_DATE(P_FECHA) WHERE COD_FACTURA = P_COD_FACTURA;
    END MOD_FECHA;
    
    FUNCTION NUM_FACTURA(P_FECHA_INICIO IN VARCHAR2, P_FECHA_FINAL IN VARCHAR2) RETURN NUMBER IS
        V_COUNT NUMBER;
    BEGIN
        SELECT COUNT(*) INTO V_COUNT FROM FACTURAS WHERE FECHA>=CONVERT_TO_DATE(P_FECHA_INICIO) AND FECHA<=CONVERT_TO_DATE(P_FECHA_FINAL);
        RETURN V_COUNT;
    END NUM_FACTURA;
    
    FUNCTION TOTAL_FACTURA(P_COD_FACTURA IN NUMBER) RETURN NUMBER IS
        V_COUNT NUMBER;
    BEGIN
        SELECT SUM(PVP*UNIDADES) INTO V_COUNT FROM LINEAS_FACTURA
        WHERE COD_FACTURA=P_COD_FACTURA;
        RETURN V_COUNT;
    END TOTAL_FACTURA;
END PF_GESTION_FACTURAS;

--PRUEBAS
SET SERVEROUTPUT ON
DECLARE 
    COUNT_FACTURAS_DATE NUMBER;
BEGIN
    --pf_gestion_facturas.alta_factura(1,'2023-10-11','NUEVOS PRODUCTOS');
    --pf_gestion_facturas.baja_factura(1);
    --pf_gestion_facturas.mod_descri(2,'SOLO PRODUCTOS NUEVOS');
    --pf_gestion_facturas.mod_fecha(2,'2023-10-1');
    --COUNT_FACTURAS_DATE:=pf_gestion_facturas.num_factura('2023-10-14','2023-10-25');
    COUNT_FACTURAS_DATE:=pf_gestion_facturas.total_factura(2);
    DBMS_OUTPUT.PUT_LINE(COUNT_FACTURAS_DATE);
END;
