--ARREGLOS
DECLARE
    TYPE DEPARTAMENTOS IS TABLE OF
    DEPARTMENTS.DEPARTMENT_NAME%TYPE
    INDEX BY PLS_INTEGER;
    
    TYPE empleados is table of
    employees%ROWTYPE 
    INDEX BY PLS_INTEGER;
    
    DEPTOS DEPARTAMENTOS;
    EMPLES EMPLEADOS;
BEGIN
    --ARRAY SIMPLES (UNA SOLA COLUMNA )
    DEPTOS(1):='INFORMATICA';
    DEPTOS(2):='RRHH';
    DBMS_OUTPUT.PUT_LINE(DEPTOS.FIRST);
    DBMS_OUTPUT.PUT_LINE(DEPTOS.LAST);
    IF DEPTOS.EXISTS(3) THEN
        DBMS_OUTPUT.PUT_LINE('EXISTE');
    ELSE
        DBMS_OUTPUT.PUT_LINE('NO EXISTE');
    END IF;
     
    --ARRAY COMPUESTOS
    SELECT * INTO EMPLES(1) FROM EMPLOYEES WHERE EMPLOYEE_ID = 100;
    SELECT * INTO EMPLES(2) FROM EMPLOYEES WHERE EMPLOYEE_ID = 110;

    DBMS_OUTPUT.PUT_LINE(EMPLES(1).FIRST_NAME);     
    DBMS_OUTPUT.PUT_LINE(EMPLES(2).FIRST_NAME);     
END;

--SELECCION MULTIPLE DE ARRAYS ASOCIATIVOS
DECLARE

    type DEPARTAMENTOS is table of
    DEPARTMENTS%ROWTYPE 
    INDEX BY PLS_INTEGER;
    DEPTOS DEPARTAMENTOS;
BEGIN
   FOR I IN 1..10 LOOP
        SELECT * INTO DEPTOS(I) FROM DEPARTMENTS WHERE
        DEPARTMENT_ID = I*10;
    END LOOP;
    
    FOR I IN DEPTOS.FIRST .. DEPTOS.LAST LOOP
        dbms_output.put_line(DEPTOS(I).DEPARTMENT_NAME);
    END LOOP;
END;
