SET SERVEROUTPUT ON
//COLECCIONES
DECLARE TYPE EMPLEADO IS RECORD(
    NOMBRE VARCHAR2(50),
    SALARIO NUMBER,
    FECHA EMPLOYEES.HIRE_DATE%TYPE,
    DATOS EMPLOYEES%ROWTYPE
);
EMPLEADO1 EMPLEADO;
EMPLEADO2 EMPLEADO;
BEGIN 
    SELECT * INTO EMPLEADO1.DATOS FROM EMPLOYEES
    WHERE EMPLOYEE_ID = 100;
    EMPLEADO1.NOMBRE:= EMPLEADO1.DATOS.FIRST_NAME || ' ' || EMPLEADO1.DATOS.LAST_NAME;
    EMPLEADO1.SALARIO:= EMPLEADO1.DATOS.SALARY *0.80;
    EMPLEADO1.FECHA:= EMPLEADO1.DATOS.HIRE_DATE;
    DBMS_OUTPUT.PUT_LINE(EMPLEADO1.NOMBRE);
    DBMS_OUTPUT.PUT_LINE(EMPLEADO1.SALARIO);
    DBMS_OUTPUT.PUT_LINE(EMPLEADO1.FECHA);
    EMPLEADO2:=EMPLEADO1;
    DBMS_OUTPUT.PUT_LINE(EMPLEADO2.NOMBRE);
END;




