SET SERVEROUTPUT ON
//CURSORES

-- Cursosres
DECLARE 
    CURSOR C1 IS SELECT * FROM REGIONS;
    V1 REGIONS%ROWTYPE;
BEGIN 
    OPEN C1;
        FETCH C1 INTO V1;
        DBMS_OUTPUT.PUT_LINE(V1.REGION_NAME);
        FETCH C1 INTO V1;
        DBMS_OUTPUT.PUT_LINE(V1.REGION_NAME);
    CLOSE C1;
END;

--Cursores en ciclos
DECLARE 
    CURSOR C1 IS SELECT * FROM REGIONS;
    V1 REGIONS%ROWTYPE;
BEGIN 
    OPEN C1;
        FETCH C1 INTO V1;
        DBMS_OUTPUT.PUT_LINE(V1.REGION_NAME);
        FETCH C1 INTO V1;
        DBMS_OUTPUT.PUT_LINE(V1.REGION_NAME);
    CLOSE C1;
END;

-- Cursores con subqueries

BEGIN
    FOR I IN (SELECT * FROM REGIONS) LOOP
          DBMS_OUTPUT.PUT_LINE(I.REGION_NAME);
    END LOOP;
END;

--Cursores con parametros
DECLARE
    CURSOR C1(SAL NUMBER) IS SELECT * FROM EMPLOYEES WHERE salary>SAL;
    EMPLES EMPLOYEES%ROWTYPE;
BEGIN
    OPEN C1(17000);
    LOOP 
        FETCH C1 INTO EMPLES;
        EXIT WHEN C1%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(EMPLES.FIRST_NAME);
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('ENCONTRE : ' || C1%ROWCOUNT || ' EMPLEADOS');
    CLOSE C1;
END;

--Cursores usados para update
DECLARE 
    EMPLES EMPLOYEES%ROWTYPE;
    CURSOR C1 IS SELECT * FROM EMPLOYEES FOR UPDATE;
BEGIN
    OPEN C1;
    LOOP 
        FETCH C1 INTO EMPLES;
        EXIT WHEN C1%NOTFOUND;
        IF EMPLES.COMMISSION_PCT IS NOT NULL THEN
            UPDATE EMPLOYEES SET SALARY = SALARY*1.10 WHERE CURRENT OF C1;
        ELSE
            UPDATE EMPLOYEES SET SALARY = SALARY*1.15 WHERE CURRENT OF C1;
        END IF;
    END LOOP;
    CLOSE C1;
END;
            
            