--PRACTICA DE COLECCIONES Y RECORDS
SET SERVEROUTPUT ON

DECLARE
    TYPE WORKER IS RECORD(
        NAME VARCHAR2(100),
        SALARIO EMPLOYEES.SALARY%TYPE,
        COD_DEPT EMPLOYEES.DEPARTMENT_ID%TYPE,
        DATA EMPLOYEES%ROWTYPE
    );
    TYPE WORKERS IS TABLE OF WORKER INDEX BY PLS_INTEGER;
    EMPLEADO WORKER;
    EMPLEADOS WORKERS;
BEGIN
    FOR I IN 100..206 LOOP
        SELECT * INTO EMPLEADO.DATA FROM EMPLOYEES WHERE EMPLOYEE_ID=I;
        EMPLEADO.NAME:=EMPLEADO.DATA.FIRST_NAME||' '||EMPLEADO.DATA.LAST_NAME;
        EMPLEADO.SALARIO:=EMPLEADO.DATA.SALARY;
        EMPLEADO.COD_DEPT:=EMPLEADO.DATA.DEPARTMENT_ID;
        EMPLEADOS(I):=EMPLEADO;
    END LOOP;
    
    --Visualizar la coleccion
    FOR I IN EMPLEADOS.FIRST .. EMPLEADOS.LAST LOOP
        EMPLEADO:=EMPLEADOS(I);
        DBMS_OUTPUT.PUT_LINE('EMPLEADO '||I||': Nombre:'||EMPLEADO.NAME||' Salario: '||EMPLEADO.SALARIO);
    END LOOP;
    
    --Visualizar el primer empleado
    EMPLEADO:=EMPLEADOS(EMPLEADOS.FIRST);
    DBMS_OUTPUT.PUT_LINE('EMPLEADO '||EMPLEADOS.FIRST||': Nombre:'||EMPLEADO.NAME||' Salario: '||EMPLEADO.SALARIO);
    
    --Visualizar el ultimo empleado
    EMPLEADO:=EMPLEADOS(EMPLEADOS.LAST);
    DBMS_OUTPUT.PUT_LINE('EMPLEADO '||EMPLEADOS.LAST||': Nombre:'||EMPLEADO.NAME||' Salario: '||EMPLEADO.SALARIO);
    
    --Visualizar el numero de empleados
    DBMS_OUTPUT.PUT_LINE('Cantidad de empleados: '||EMPLEADOS.COUNT);
    
    --Borrar a los empleados que ganan < 7000
    FOR I IN EMPLEADOS.FIRST .. EMPLEADOS.LAST LOOP
        EMPLEADO:=EMPLEADOS(I);
        IF EMPLEADO.SALARIO < 7000 THEN
            EMPLEADOS.DELETE(I);
        END IF;
    END LOOP;
    
    --Visualizar el numero de empleados
    DBMS_OUTPUT.PUT_LINE('Cantidad de empleados: '||EMPLEADOS.COUNT);
END;